# -*- coding: utf-8 -*-
"""week_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12sGJVDMPoSYkA8o3WqFx67rEDn3WvDCZ

##프로그래밍이란?
- 프로그래밍 언어를 사용하여 프로그램을 개발하는 것
- 논리적인 사고를 가질 수 있다.

##programming language?
 - 프로그램을 개발할 때 사용하는 도구
 - 인간이 원하는 것을 컴퓨터에 명령할 때 사용하는 컴퓨터가 이해할 수 있는 언어
##파이썬? 
 - 쉽다, 간결하다
 - 라이브러리가 많다

###Chapter 2. Data: Types, Values, Variables, and Names
"""

a=2
a

a==2

"""

- 변수|variable: 특정 값을 저장하는 공간 
  a
- 값|value 
  2

- 할당하다|assign: 변수에 값을 넣는 과정
  "2를 a에 넣었다."

 *** a는 2다. a==2
 - 자료형|type: 데이터의 형태
   a데이터의 형태? integer(int타입이다.)
   
 """

print(a)

a

#type
type(a)

type(2)

type(a == 2)

"""##Type
- integer|정수: 1,2,3 |int
- floating point number|부동소수점: 1.0,2.0,...0.4 |float
- string|문자열:"1", 'apple' |str
- boolean|불리안: True/False |bool












"""

type("1")

type('apple')

type(apple)

name='kim'

name

"""###할당
- = 기호 사용
- 수학에서는 '양변이 같다'라는 의미로 사용되지만, 프로그래밍에서는 '할당하다'라는 의미가 추가된다.
- "오른쪽의 값을 왼쪽에 할당하다."
   - 1. 오른쪽에 있는 모든 것은 값을 가져야 한다. (초기화를 해야 한다.)
   - 2. 같은 변수에 다른 값을 넣을 수 있다.



"""

x = 4 #초기화
y = x + 3

x, y

name = 'kim'
name = 'lee'
name = 'park'
name = 4

print(name) #변수명 동일하게 사용하지 x

### 변수명 정하기

"""### 변수명 정하기
- 나쁜 변수명: a, b, c, a1, b1 등
- 의미있는 이름으로 선언해야 한다.
- 소문자, 대문자, 숫자, 언더바를 사용한다.예) name, name2, my_name, Name, NAME

"""

name = 'juliette'
name1 = 'jessica'
my_name = 'Laura'
#myName 카멜표기법
print(name, name1, my_name, sep=',')



"""- 안되는 것
  - 숫자로 시작할 수 없다.
    예: 22name, 22_name
  - 예약어로 선언할 수 없다.
    예: def, False

"""

# if = 'kim'
help("keywords")



"""조심할 것
  - 언더바로 시작하는 변수명 (_name)
  - 더블 언더바로 시작하는 변수명 (__name)
  - 대문자로 시작하는 변수명 (Name)
  - 전체 대문자 (NAME)
"""

#변수명은 대소문자 구분한다.
num = 43
NUM = 44

num == NUM

num != NUM



"""##복습


---



"""

name = 1
bday = 1103

"""- 실행: shift enter 동시에 누르기"""

print(name)

print(bday)

name == 1

bday == 1103

type(name)

type(bday)

type(name==2)

type('bday')

type(name=2)

name == 2

name !=2

print(name, bday,sep=',')

print(bday, name, sep='/')

school = 'HUFS'

school

print(school)

x = 1
y = 7

x + y

print(x,y)

a = 3
b = a +7
print(b)

type(b)

type(x)

b == 10

